### ISSUE TITLE
Not working with videojs player v5.00

### ISSUE THREAD

**Issue by astr0junk** [MailOnline/videojs-vast-vpaid#74]

**Comment by carpasse** [comment]
Videojs player V5.00 was officially released 9 days ago I believer. 
I am going to mark this issue as enhancement. Unfortunately we currently have our hands full with new functionalities and it may take a month or two before we can give support for V5.00.

Would you be open to do it? If not we will do it but once we have implemented midroll and postroll ads. It is just more important for us right now.

**Comment by kahwee** [comment]
I can do this. How would you recommend it to be done? 

The code might diverge due to ES6 enhancements.

**Comment by DrLightman** [comment]
I'm looking forward to this.

**Comment by vzhivkov** [comment]
kahwee's changes does help a bit but still have issues - the progress bar during the advert is not working even though on the right it shows the correct advert duration and the "rolling circle" in the center of the video doesn't hide as it should when the advert is loaded and running

**Comment by wmcmurray** [comment]
+1

**Comment by trucle** [comment]
+1

**Comment by Fetz** [comment]
This should be working now for videojs 5x. So will close this issue
